export type MotivationalPhrase = { en: string; es: string };

export const MOTIVATIONAL_PHRASES: MotivationalPhrase[] = [
  { en: "You are not waiting for your moment—you are creating it.", es: "No estás esperando tu momento: lo estás creando." },
  { en: "Your vision deserves the work it demands.", es: "Tu visión merece todo el trabajo que exige." },
  { en: "She believed in herself before anyone else did.", es: "Ella creyó en sí misma antes que los demás." },
  { en: "Your consistency will take you where motivation cannot.", es: "Tu constancia te llevará adonde la motivación no puede." },
  { en: "Create boldly. Live authentically. Rise unapologetically.", es: "Crea con valentía. Vive con autenticidad. Brilla sin pedir disculpas." },
  { en: "You were not made to fit in—you were made to leave a mark.", es: "No naciste para encajar, sino para dejar tu huella." },
  { en: "Every small step is building the woman you are becoming.", es: "Cada pequeño paso construye a la mujer en la que te estás convirtiendo." },
  { en: "Your dreams need discipline, not permission.", es: "Tus sueños necesitan disciplina, no permiso." },
  { en: "Your voice is powerful. Use it.", es: "Tu voz tiene poder. Úsala." },
  { en: "You are the creator of your content and the author of your destiny.", es: "Eres la creadora de tu contenido y la autora de tu destino." },
  { en: "The work nobody sees creates the success everyone notices.", es: "El trabajo que nadie ve crea el éxito que todos admiran." },
  { en: "You do not need to be perfect to be unforgettable.", es: "No necesitas ser perfecta para ser inolvidable." },
  { en: "Your authenticity is your greatest advantage.", es: "Tu autenticidad es tu mayor ventaja." },
  { en: "Keep showing up. Your future is watching.", es: "Sigue apareciendo. Tu futuro te está observando." },
  { en: "Build the life you once needed permission to imagine.", es: "Construye la vida que antes necesitabas permiso para imaginar." },
  { en: "Your confidence grows every time you keep a promise to yourself.", es: "Tu confianza crece cada vez que cumples una promesa que te hiciste." },
  { en: "Rest when you need to, but never abandon yourself.", es: "Descansa cuando lo necesites, pero nunca te abandones." },
  { en: "The woman you are becoming is worth the effort.", es: "La mujer en la que te estás convirtiendo merece todo el esfuerzo." },
  { en: "You are allowed to outgrow every version of yourself.", es: "Tienes permiso para superar cada versión anterior de ti misma." },
  { en: "Your ideas are worthy of being seen.", es: "Tus ideas merecen ser vistas." },
  { en: "Do not shrink your dreams to fit someone else's comfort.", es: "No reduzcas tus sueños para acomodarte a la comodidad de otros." },
  { en: "You are not behind. You are building something real.", es: "No estás atrasada. Estás construyendo algo real." },
  { en: "Turn pressure into purpose and effort into impact.", es: "Convierte la presión en propósito y el esfuerzo en impacto." },
  { en: "She stopped doubting herself and started changing her life.", es: "Ella dejó de dudar de sí misma y comenzó a transformar su vida." },
  { en: "Your passion opened the door; your discipline will keep it open.", es: "Tu pasión abrió la puerta; tu disciplina la mantendrá abierta." },
  { en: "You carry everything you need to begin again.", es: "Llevas dentro de ti todo lo necesario para comenzar de nuevo." },
  { en: "Be proud of the days you kept going quietly.", es: "Siéntete orgullosa de los días en que seguiste adelante en silencio." },
  { en: "Your glow comes from choosing yourself every day.", es: "Tu brillo nace de elegirte cada día." },
  { en: "Success looks beautiful on a woman who earned it.", es: "El éxito luce hermoso en una mujer que se lo ganó." },
  { en: "Your future is being shaped by what you do today.", es: "Tu futuro está siendo formado por lo que haces hoy." },
  { en: "Make your presence as powerful as your purpose.", es: "Haz que tu presencia sea tan poderosa como tu propósito." },
  { en: "You are becoming proof that courage changes everything.", es: "Te estás convirtiendo en la prueba de que el valor lo cambia todo." },
  { en: "Create even when no one is watching.", es: "Crea incluso cuando nadie esté mirando." },
  { en: "Your value is not measured by views, likes, or numbers.", es: "Tu valor no se mide en vistas, \"me gusta\" ni números." },
  { en: "Protect your peace, honor your pace, and trust your process.", es: "Protege tu paz, respeta tu ritmo y confía en tu proceso." },
  { en: "The world does not need another copy. It needs your truth.", es: "El mundo no necesita otra copia. Necesita tu verdad." },
  { en: "Work until your reality reflects your vision.", es: "Trabaja hasta que tu realidad refleje tu visión." },
  { en: "You can be soft, powerful, ambitious, and kind—all at once.", es: "Puedes ser sensible, poderosa, ambiciosa y bondadosa al mismo tiempo." },
  { en: "One day, you will thank yourself for refusing to quit.", es: "Un día te agradecerás por haberte negado a renunciar." },
  { en: "This is not just content. This is your legacy in motion.", es: "Esto no es solo contenido. Es tu legado en movimiento." },
];
